apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller-metrics-auth
  labels:
    {{ include "sbombastic.labels" .| nindent 4 }}
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sbombastic.fullname" . }}-controller-metrics-auth
subjects:
- kind: ServiceAccount
  name: {{ include "sbombastic.fullname" . }}-controller
  namespace: system
