apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller-metrics-auth
  labels:
    {{ include "sbombastic.labels" .| nindent 4 }}
    app.kubernetes.io/component: controller
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
