apiVersion: v1
kind: Service
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sbombastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    {{- include "sbombastic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
